name: facturamobile
description: &#x27;A new Flutter project. Created by Slidy&#x27;

version: 1.5.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  dio: ^3.0.9
  http: ^0.12.0+4
  bottom_navy_bar: ^5.4.0
  flutter_mobx: ^1.1.0
  flutter_secure_storage: ^3.3.2
  mobx: ^1.1.1
  flutter_modular: ^1.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.1
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/design_course/
    - assets/fitness_app/
    - assets/hotel/